apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-webapp
spec:
  source:
    git:
      ref: main
      uri: 'https://github.com/atwatanmalikm/simple-webapp.git'
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'webapp:'
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: webapp

